### ISSUE TITLE
Need help on converting accData to engineering units

### ISSUE THREAD

**Issue by Piks19** [YunSolutions/levin-openData#1]
I can't convert the accData to engineering units because don't know how the mx, my and mz are computed in `[mx,my,mz] = df_trip[['mx', 'my', 'mz']][df_trip['speed'] <= 1].mean().tolist()`

**Comment by lalitk06110** [comment]
Updated the [data_extract.ipynb](https://github.com/YunSolutions/levin-openData/blob/master/data_extract.ipynb) to include functions for magnetometer data conversion.
